name: ${PROJECT_NAME}

include: # Please keep alphabetic order
  - adminer/docker-compose-adminer.yml
  - 2faserver/docker-compose-2faserver.yml
  - backend/docker-compose-backend.yml  
  - dbserver/docker-compose-dbserver.yml
  - frontend/docker-compose-frontend.yml
  - grafana/docker-compose-grafana.yml
  - auth-frontend/docker-compose-auth-frontend.yml
  - auth-service/docker-compose-auth-service.yml

networks:
  transcendence_net:
    name: thenet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/28  # Define the IP range
  auth_net:
    internal: true # Aislada del mundo exterior
  db_net:
    internal: true # Solo compartida con la base de datos

volumes:
  volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: "${TRANSCENDENCE_HOME}/data/dbserver"
      o: bind
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: "${TRANSCENDENCE_HOME}/data/grafana"
      o: bind

