name: ${PROJECT_NAME}

include: # Please keep alphabetic order
  - adminer/docker-compose-adminer.yml
  #- path ./2faserver/docker-compose-2faserver.yml
  #- path ./backendserver/docker-compose-backendserver.yml  
  - dbserver/docker-compose-dbserver.yml
  #- path ./frontendserver/docker-compose-frontendserver.yml
  - grafana/docker-compose-grafana.yml

networks:
  transcendence_net:
    name: thenet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/28  # Define the IP range


volumes:
  volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: "${TRANSCENDENCE_HOME}/data/dbserver"
      o: bind
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: "${TRANSCENDENCE_HOME}/data/grafana"
      o: bind

