name: ${PROJECT_NAME}

include: # Please keep alphabetic order
  - adminer/docker-compose-adminer.yml
  #- path ./2faserver/docker-compose-2faserver.yml
  - backend/docker-compose-backend.yml  
  - dbserver/docker-compose-dbserver.yml
  - frontend/docker-compose-frontend.yml
  - grafana/docker-compose-grafana.yml

networks:
  transcendence_net:
    name: thenet
    driver: bridge
    ipam:
      config:
        # - subnet: 192.168.1.0/28  # Define the IP range
        - subnet: 172.20.0.0/28


volumes:
  volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: "${TRANSCENDENCE_HOME}/data/dbserver"
      o: bind
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: "${TRANSCENDENCE_HOME}/data/grafana"
      o: bind

