  # Backend: Usando HTTPS obligatorio 
  backend:
    build: ./src/backend
    container_name: transcendence_backend
    volumes:
      - ./src/backend:/app
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - ft_network
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"