services:
  totp:
    build:
      context: .
      args:
        TOTP_CONTAINER_PORT: ${TOTP_CONTAINER_PORT}
    container_name: ${TOTP_CONTAINER_NAME}
    image: ${TOTP_CONTAINER_NAME}
    ports:
      - ${TOTP_CONTAINER_PORT}:${TOTP_CONTAINER_PORT}
    volumes:
      - .:/app
    networks:
      transcendence_net:
        ipv4_address: ${TOTP_IP}  # Fixed IP
        aliases:
          - in_net
    env_file:
      - ../.env
    restart: always

