  # Frontend: Debe ser responsivo y accesible [cite: 179]
  frontend:
    build: ./src/frontend
    container_name: transcendence_frontend
    volumes:
      - ./src/frontend:/app
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    networks:
      - ft_network