services:
  auth-frontend:
    build: .
    container_name: ${AUF_CONTAINER_NAME}
    image: ${AUF_CONTAINER_NAME}
    restart: on-failure      
    ports:
      - ${AUF_PORT}:${AUF_PORT} # Accedemos por el 5174 para evitar conflictos
    env_file:
      - ../.env
    networks:
      transcendence_net:
        ipv4_address: ${AUF_IP}  # Fixed IP
        aliases:
          - in_net