apiVersion: 1

datasources:
  - name: Postgres_Transcendence
    uid: transcendence_001
    type: postgres
    url: ${DB_HOST}:${DB_PORT}
    database: ${DB_NAME}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: 'disable' # Para desarrollo local
      postgresVersion: ${DB_VERSION}