services:

  adminer:
    image: ${ADMINER_IMAGE}
    restart: always
    container_name: ${ADMINER_CONTAINER_NAME}    
    ports:
      - ${ADMINER_CONTAINER_PORT}:${ADMINER_CONTAINER_PORT} # Puerto para Adminer
    networks:
      transcendence_net:
        ipv4_address: ${AD_IP}  # Fixed IP
        aliases:
          - in_net